local h_str = {}

h_str.acquire_input_focus = hash("acquire_input_focus")

h_str.collection_main = hash("collection_main")
h_str.collection_overworld = hash("collection_overworld")
h_str.collection_dialog = hash("collection_dialog")
h_str.collection_start = hash("collection_start")
h_str.collection_inventory = hash("collection_inventory")
h_str.collection_party = hash("collection_party")

h_str.init_monarch = hash("init_monarch")

h_str.key_f11 = hash("key_f11")
h_str.key_up = hash("key_up")
h_str.key_left = hash("key_left")
h_str.key_down = hash("key_down")
h_str.key_right = hash("key_right")
h_str.key_z = hash("key_z")
h_str.key_x = hash("key_x")
h_str.key_enter = hash("key_enter")
h_str.key_lctrl = hash("key_lctrl")

h_str.message_trigger_event = hash("message_trigger_event")
h_str.message_set_receiver = hash("message_set_receiver")
h_str.message_character_turn = hash("message_character_turn")
h_str.message_character_walk = hash("message_character_walk")
h_str.message_unhook_command = hash("message_unhook_command")

h_str.message_command_lock = hash("message_command_lock")
h_str.message_command_unlock = hash("message_command_unlock")
h_str.message_command_load_dialog = hash("message_command_load_dialog")
h_str.message_command_start_dialog = hash("message_command_start_dialog")
h_str.message_command_close_dialog = hash("message_command_close_dialog")

h_str.animation_idle_up = hash("idle_up")
h_str.animation_idle_left = hash("idle_left")
h_str.animation_idle_down = hash("idle_down")
h_str.animation_walk_up_left = hash("walk_up_left")
h_str.animation_walk_up_right = hash("walk_up_right")
h_str.animation_walk_left_left = hash("walk_left_left")
h_str.animation_walk_left_right = hash("walk_left_right")
h_str.animation_walk_down_left = hash("walk_down_left")
h_str.animation_walk_down_right = hash("walk_down_right")
h_str.animation_run_up_left = hash("run_up_left")
h_str.animation_run_up_right = hash("run_up_right")
h_str.animation_run_left_left = hash("run_left_left")
h_str.animation_run_left_right = hash("run_left_right")
h_str.animation_run_down_left = hash("run_down_left")
h_str.animation_run_down_right = hash("run_down_right")

h_str.layer_collision = hash("layer_collision")
h_str.layer_terrain = hash("layer_terrain")
h_str.layer_object = hash("layer_object")
h_str.layer_canopy = hash("layer_canopy")

h_str.collision_passable = hash("passable")
h_str.collision_impassable = hash("impassable")
h_str.collision_water = hash("water")

h_str.font_monogram = hash("monogram")

h_str.node_dialog_background = hash("node_dialog_background")
h_str.node_spinner = hash("node_spinner")
h_str.node_selector = hash("node_selector")
h_str.node_inventory = hash("node_inventory")
h_str.node_party = hash("node_party")
h_str.node_terraglyphs = hash("node_terraglyphs")
h_str.node_map = hash("node_map")
h_str.node_records = hash("node_records")
h_str.node_settings = hash("node_settings")
h_str.node_save = hash("node_save")
h_str.node_label = hash("node_label")
h_str.node_section = hash("node_section")
h_str.node_action_background = hash("node_action_background")
h_str.node_use = hash("node_use")
h_str.node_equip = hash("node_equip")
h_str.node_consume = hash("node_consume")
h_str.node_drop = hash("node_drop")
h_str.node_party_background = hash("node_party_background")
h_str.node_stats_background = hash("node_stats_background")
h_str.node_health_stats = hash("node_health_stats")
h_str.node_strength_stats = hash("node_strength_stats")
h_str.node_defense_stats = hash("node_defense_stats")
h_str.node_agility_stats = hash("node_agility_stats")
h_str.node_wonder_stats = hash("node_wonder_stats")
h_str.node_terra_stats = hash("node_terra_stats")
h_str.node_health_delta = hash("node_health_delta")
h_str.node_strength_delta = hash("node_strength_delta")
h_str.node_defense_delta = hash("node_defense_delta")
h_str.node_agility_delta = hash("node_agility_delta")
h_str.node_wonder_delta = hash("node_wonder_delta")
h_str.node_terra_delta = hash("node_terra_delta")
h_str.node_equipable = hash("node_equipable")
h_str.node_not_equipable = hash("node_not_equipable")

return h_str